# ****Numpy Python Module****

NumPy, short for Numerical Python, is an open-source Python library designed to handle numerical computations efficiently. It provides support for multi-dimensional arrays (like tables and matrices), allowing you to work with large datasets and perform mathematical operations on them quickly. NumPy includes a wide range of mathematical functions, such as calculating averages, sums, and applying complex operations like matrix multiplication or statistical analysis, all with minimal code. It is widely used in scientific computing, data analysis, and machine learning because of its speed and ease in handling large volumes of numerical data, making it an essential tool in these fields.

## Applications

- Data Analysis: NumPy allows you to create and manipulate data (in the form of arrays), filter it, and perform operations like calculating the mean, standard deviation, etc.

- Machine Learning & AI: Libraries like TensorFlow and PyTorch use NumPy to manage input data, model parameters, and process output values.

- Array Manipulation: NumPy supports creating, resizing, slicing, indexing, stacking, splitting, and combining arrays.

- Finance & Economics: NumPy is used for financial analysis, including portfolio optimization, risk assessment, time series analysis, and statistical modeling.

- Image & Signal Processing: NumPy helps in processing and analyzing images and signals for various applications.

- Data Visualization: While NumPy itself doesn’t generate visualizations, it works with libraries like Matplotlib and Seaborn to create charts and graphs from numerical data.


## Why is NumPy Faster Than Lists?

| **Aspect**        | **NumPy**                                                                                           | **Python List**                                                                                                  |
|-------------------|-----------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------|
| **Memory Storage** | NumPy stores all data in one continuous block, making it faster to access and use less memory.                   | Python lists store references to objects, which can slow things down and use more memory.                        |
| **Data Types**     | NumPy arrays have elements of the **same type**, which helps save memory and makes things faster.               | Python lists can hold elements of **different types**, which takes up more memory and makes things slower.      |
| **Operations**     | NumPy can do math on entire arrays at once, making it faster.                                                   | Python lists need loops to do math on each element one by one, which is slower.                                |
| **Efficiency**     | NumPy is written in **C**, making it much faster for numerical tasks.                                          | Python lists are slower because they are handled by Python’s slower byte-code.                                  |
| **Memory Usage**   | NumPy uses less memory because all elements are the same type and stored in one place.                         | Python lists use more memory because each element is a separate object.                                         |
| **Broadcasting**   | NumPy allows you to do operations on arrays of different sizes without copying data, making it faster.         | Python lists can't do this, so operations on different sized lists take longer.                                |
| **Performance**    | NumPy is faster because it uses memory better and does things more efficiently.                                | Python lists are slower because their data is scattered around in memory.                                      |
| **Functionality**  | NumPy has many built-in math functions for arrays, making it perfect for complex calculations.                 | Python lists only have basic functions and can’t handle complex math easily.                                   |                               |


In [13]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
print(array.dtype)  # Output: <class 'numpy.ndarray'>
array

int64


array([1, 2, 3, 4, 5])

## NumPy ndarray:
- ndarray (short for N-dimensional array) is the **core object** in NumPy.

- It represents a collection of items (elements) that are all of the same type.

- Each element in the ndarray can be accessed using a zero-based index.

- All elements of an ndarray take the same size block in memory.

- The type of the elements is defined by a special object called **dtype** (data type), which specifies how much memory each element takes and what type it is (e.g., integer, float).

## Relationship Between ndarray, dtype, and Array Scalar Types:
- **ndarray**: This is the main object that holds the array of data.

- **dtype**: This is the data type object that defines the type of each element within the ndarray (e.g., int32, float64).

- **Array Scalar Type**: When you extract an element from an ndarray (like by slicing), the element is converted into a Python object of a specific array scalar type, which corresponds to the dtype of the ndarray.

### **Creating an ndarray with numpy.array()**
The numpy.array() function is the most common way to create an ndarray. It takes in any object that can expose the array interface or any sequence (like lists, tuples, or nested sequences). Here's the basic syntax:

In [3]:
np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

array(<class 'object'>, dtype=object)

**parameters taken are as follows**


| **Sr.No.** | **Parameter** | **Description** | **Example** |
|------------|---------------|-----------------|-------------|
| 1 | **`object`** | This is the data (like a list, tuple, or another array) that you want to convert into a NumPy array. It is the most important argument. | `np.array([1, 2, 3, 4])` creates an array from a list. |
| 2 | **`dtype`** | Specifies the desired data type for the array elements (e.g., `int`, `float`). If not specified, NumPy tries to infer the data type. refer official doc for knowing about suported dtypes | `np.array([1, 2, 3], dtype=np.float32)` creates an array with `float32` type. |
| 3 | **`copy`** | By default, this is `True`, meaning a new copy of the data is made. If set to `False`, NumPy will use a reference to the original data. | `np.array([1, 2, 3], copy=False)` creates a reference to the input list. |
| 4 | **`order`** | Specifies how the array is stored in memory. `'C'` is for row-major (C-style), and `'F'` is for column-major (Fortran-style). | `np.array([[1, 2], [3, 4]], order='F')` creates a 2D array in column-major order. |
| 5 | **`subok`** | If `True`, sub-classes of `ndarray` (like masked arrays) are preserved when returning the array. If `False` (default), the result is always a base `ndarray`. | `np.array([1, 2, 3], subok=True)` keeps any subclass of `ndarray`. |
| 6 | **`ndmin`** | Specifies the minimum number of dimensions for the resulting array. If the input has fewer dimensions, extra dimensions are added. | `np.array([1, 2, 3], ndmin=2)` converts the 1D array to a 2D array with shape `(1, 3)`. |


## Example: Create a One-dimensional Array

In [4]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

## Example: Create a Multi-dimensional Array

In [24]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

a = np.array([range(i,i+2) for i in [1,3]])
a

[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

## Example: Specify Minimum Dimensions

In [8]:
import numpy as np
a = np.array([1, 2, 3, 4, 5], ndmin=2)
a

array([[1, 2, 3, 4, 5]])

## Example: Specify Data Type

In [10]:
import numpy as np
a = np.array([1, 2, 3], dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

# **Indexing Scheme**

The indexing scheme in NumPy determines how elements in an ndarray are located in memory using a combination of shape and strides.

## Shape and Strides in NumPy
**Shape**:

- The shape of an ndarray represents the size of the array along each dimension. It is a tuple of integers.

- Example: For a 2x3 array, the shape would be (2, 3). This means there are 2 rows and 3 columns.

**Strides**:

- Strides refer to the number of bytes you need to move in memory to access the next element in each dimension. It tells NumPy how to step across the dimensions of the array when moving through its elements.

- For instance, in a 2D array, the stride value for each dimension tells you how many bytes to move from one element to the next element in the same row (along the row axis) or to the next element in the same column (along the column axis).

# **Row-major and Column-major Orders**

**Row-major Order (C-style):**

- In row-major order, the last index changes the fastest. This means that elements in the same row are stored next to each other in memory.

- For example, in a 2x3 array like:

[[1, 2, 3],
 [4, 5, 6]]

The elements will be stored in memory as:
1, 2, 3, 4, 5, 6.

**Column-major Order (FORTRAN-style):**

- In column-major order, the first index changes the fastest. This means that elements in the same column are stored next to each other in memory.

- For example, in the same 2x3 array:

[[1, 2, 3],
 [4, 5, 6]]

The elements will be stored in memory as:
1, 4, 2, 5, 3, 6.


**Example**

Following is a basic example to demonstrate the usage of the memory layout −


In [11]:
import numpy as np

# Creating a 2x3 array in row-major order
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("Shape:", a.shape)
print("Strides:", a.strides)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Strides: (24, 8)


The shape of the array is (2, 3), indicating it has 2 rows and 3 columns. The strides are (24, 8), meaning that to move to the next row, we need to skip 24 bytes (since each element is an 8-byte integer, and there are 3 columns), and to move to the next column, we need to skip 8 bytes (the size of one integer)

------------------------------------------

# *Creating Numpy arrays*

In NumPy, you can create arrays using several built-in functions, each of which serves a different purpose depending on the type of array you want to create. Here’s a breakdown of some of the most commonly used functions for creating NumPy arrays:

### 1. **`numpy.array()`**
- Converts a list or other sequence into a NumPy array.
- **Example**: `np.array([1, 2, 3])` turns a list into an array.

### 2. **`numpy.zeros()`**
- Creates an array filled with zeros.
- **Example**: `np.zeros((2, 3))` creates a 2x3 array of zeros.

### 3. **`numpy.ones()`**
- Creates an array filled with ones.
- **Example**: `np.ones((3, 2))` creates a 3x2 array of ones.

### 4. **`numpy.arange()`**
- Creates an array with numbers in a specified range, with a specific step size.
- **Example**: `np.arange(0, 10, 2)` creates an array with numbers from 0 to 10, stepping by 2 (i.e., `[0, 2, 4, 6, 8]`).

### 5. **`numpy.linspace()`**
- Creates an array with evenly spaced numbers over a specified range.
- **Example**: `np.linspace(0, 1, 5)` creates 5 evenly spaced numbers between 0 and 1.

### 6. **`numpy.random.rand()`**
- Creates an array of random numbers between 0 and 1.
- **Example**: `np.random.rand(2, 3)` creates a 2x3 array of random numbers.

### 7. **`numpy.empty()`**
- Creates an array without initializing the values, meaning the array will contain random data initially.
- **Example**: `np.empty((2, 2))` creates an empty 2x2 array with uninitialized values.

### 8. **`numpy.full()`**
- Creates an array filled with a specific value that you provide.
- **Example**: `np.full((3, 3), 7)` creates a 3x3 array filled with the value `7`.


### **Example: Creating a 1D & 2D NumPy Array uing list as input for numpy.array()**

In [ ]:
import numpy as np

# Creating a 1D array from a list
# syntax - numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0, like=None)

my_list = [1, 2, 3, 4, 5] #my_list - object list
my_array = np.array(my_list)

print("1D Array:", my_array)

# Creating a 2D array from a list of lists
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("2D Array(2x3):\n", arr)


1D Array: [1 2 3 4 5]
2D Array(2x3):
 [[1 2 3]
 [4 5 6]]


### **Example: Creating a NumPy Array with values initialized to zeroes**

In [ ]:
import numpy as np

# Creating an array of zeros 

# syntax - numpy.zeros(shape, dtype=float, order='C')

# here order desides whether to save in row major or column major memory layout indexing
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


### **Example: Creating a 1D & 2D NumPy Array with values initialized to one**

In [ ]:
import numpy as np

# Creating an array of ones 
# syntax - numpy.ones(shape, dtype=None, order='C')
arr = np.ones(3)
print("1D Array:", arr)

# Creating 2D array of ones 
array_2d = np.ones((2, 3), dtype=np.int32, order='F')
print("2D Array(2x3):\n", array_2d)
print("strides for 2d for int32 dtype with Fortran style indexing: ", array_2d.strides)

1D Array: [1. 1. 1.]
2D Array(2x3):
 [[1 1 1]
 [1 1 1]]
strides for 2d for int32 dtype with Fortran style indexing:  (4, 8)


### **Using numpy.arange() Function**

The numpy.arange() function generates a sequence of numbers in a specified range. You can define three parameters:

- start: The starting value of the sequence (defaults to 0 if not provided).

- stop: The end value of the sequence (exclusive, not included in the result).

- step: The interval between consecutive values (defaults to 1 if not provided).

It creates an array with evenly spaced numbers based on the start, stop, and step values.

### **Example for numpy.arrange()**

In [44]:
import numpy as np

# Providing just the stop value
array1 = np.arange(10)
print("array1:", array1)

# Providing start, stop and step value
array2 = np.arange(1, 10, 2)
print("array2:",array2)

array1: [0 1 2 3 4 5 6 7 8 9]
array2: [1 3 5 7 9]


### **Using numpy.linspace() Function:**
The numpy.linspace() function generates a sequence of evenly spaced numbers over a specified range. Unlike numpy.arange(), which generates numbers based on a specified step size, numpy.linspace() generates a fixed number of points between a given start and stop value.

**Parameters:**
- start: The starting value of the sequence.

- stop: The end value of the sequence (inclusive by default).

- num: The number of samples to generate. This is the total number of equally spaced points between start and stop (defaults to 50).

- endpoint: If True (default), stop is included in the sequence. If False, stop is excluded.

- retstep: If True, returns a tuple of the array and the step size used to generate it.

- dtype: The data type of the returned array.

- axis: The axis in the result along which the numbers are spaced.

In [ ]:
import numpy as np

# syntax - numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

# Creating an array of 10 evenly spaced values from 0 to 5
array1 = np.linspace(0, 5, num=10, dtype=np.float16)
print("array1:",array1)


# Creating an array with 5 values from 1 to 2, excluding the endpoint
array2 = np.linspace(1, 2, num=5, endpoint=False)
print("array2:",array2)

# Creating an array and returning the step value
array3, step = np.linspace(0, 10, num=5, retstep=True)
print("array3:",array3)
print("Step size:", step)

array1: [0.     0.5557 1.111  1.667  2.223  2.777  3.334  3.889  4.445  5.    ]
array2: [1.  1.2 1.4 1.6 1.8]
array3: [ 0.   2.5  5.   7.5 10. ]
Step size: 2.5


### **Using numpy.random.rand() Function**:

The `numpy.random.rand()` function creates an array filled with random values sampled from a uniform distribution over the interval [0, 1). This means that the values generated will lie between 0 and 1 (excluding 1).

### **Example**


In [ ]:
import numpy as np

# syntax - numpy.random.rand(d0, d1, ..., dn)

# 1. Generating a single random float
random_float = np.random.rand()
print("Single random float:", random_float)

# 2. Generating a 1D array of 5 random floats
array_1d = np.random.rand(5)
print("1D array of random values:", array_1d)

# 3. Generating a 2D array (2 rows, 3 columns) of random floats
array_2d = np.random.rand(2, 3)
print("2D array of random values:\n", array_2d)

# 4. Generating a 3D array (2 matrices of 3x4) of random floats
array_3d = np.random.rand(2, 3, 4)
print("3D array of random values:\n", array_3d)


Single random float: 0.7784984015398853
1D array of random values: [0.71396663 0.70221603 0.73358819 0.49960377 0.71924999]
2D array of random values:
 [[0.41517704 0.69093719 0.96939421]
 [0.48131649 0.8673289  0.24330281]]
3D array of random values:
 [[[0.47340948 0.76750561 0.25541448 0.21200211]
  [0.26186534 0.9798382  0.10978586 0.63319182]
  [0.91764192 0.77868094 0.29401364 0.94364847]]

 [[0.41786508 0.5619276  0.45035133 0.30837811]
  [0.28266208 0.69010672 0.42274183 0.30142177]
  [0.44635208 0.59130415 0.41945825 0.28428521]]]


### **Using numpy.empty() Function**:

- **`numpy.empty()`** creates an array with the specified shape.
- The values inside the array are **random** and uninitialized, depending on the memory state.
- It is useful when you need to create an array **quickly** without filling it with values immediately.
- Unlike `numpy.zeros()` (which fills the array with zeros) or `numpy.ones()` (which fills the array with ones), `numpy.empty()` does not initialize the array.
- It is faster and saves memory because it doesn’t waste time initializing the array.
- Best used when you plan to **fill** the array with your own data later.

### **Example**

In [ ]:
import numpy as np

# syntax - numpy.empty(shape, dtype=float, order='C')

empty_array = np.empty((2, 3))
print("array init with random values:\n",empty_array)

array init with random values:
 [[0.41517704 0.69093719 0.96939421]
 [0.48131649 0.8673289  0.24330281]]


### Explanation of `numpy.full()` Function

The `numpy.full()` function is used to create a NumPy array of a specific shape and fill it with a **specified value**. This is useful when you want to initialize an array with a specific number across all its elements.

### **paramters:**

- **shape**: Specifies the dimensions of the array (e.g., (2, 3) for a 2x3 array).

- **fill_value**: The value with which the array is filled. This value will be assigned to all elements of the array.

- **dtype**: Optional. Specifies the data type of the array elements. The default is None, meaning the data type is inferred from the fill value.

- **order**: Optional. Specifies the memory layout order ('C' for row-major, 'F' for column-major). It is not commonly used unless you have specific requirements.

In [ ]:
import numpy as np

# syntax - numpy.full(shape, fill_value, dtype=None, order='C')

array1 = np.full((2, 3), 5)
print(array1)

### Functions Used for Creation of NumPy Arrays

In the NumPy module, there are various ways to create NumPy arrays that include basic creation methods, creation by reshaping and modifying data, creation using sequences, and creation using random functions. For further details on the creation functions, please refer to the official NumPy documentation.

----------------------------------------------------------------

## **Manipulating the Shape of Arrays in NumPy**

Several routines are available in NumPy for manipulating the shape of elements in an ndarray object. These routines allow you to change the shape without altering the data, making it easier to work with different dimensions. The following functions are used for changing the shape of arrays:

## Frequently Used Functions

### Reshape and Flattening
- `reshape()`, `flatten()`, `ravel()` — Machine learning, data preprocessing.

### Transpose
- `transpose()`, `swapaxes()` — Linear algebra, deep learning.

### Joining Arrays
- `concatenate()`, `vstack()`, `hstack()` — Data preparation, feature engineering.

### Sorting and Searching
- `sort()`, `argsort()`, `argmax()` — Data analysis, optimization tasks.

### Broadcasting
- `broadcast_to()`, `expand_dims()` — Handling arrays of different shapes for operations.

### Set Operations
- `unique()`, `in1d()` — Data cleaning, analysis.








### 1. Numpy `reshape()` Function

The `reshape()` function in NumPy is used to change the shape of an array, but the data in the array stays the same. It doesn't change the values inside; it just rearranges them into a new shape based on the dimensions you provide. The total number of elements must remain the same, meaning the number of elements in the original array must match the number of elements in the reshaped array.

### Syntax:
```python
numpy.reshape(arr, newshape, order='C')

### Parameters:
- arr: The input array that you want to reshape.

- newshape: A new shape for the array. This can be a single integer or a tuple of integers. The new shape must be compatible with the total number of elements in the original array.

- order: (Optional) This specifies how the array should be read and written:

  'C': Row-major order (default).

  'F': Column-major order.

### Return Value:
The function returns a new array with the same data but a different shape.

### Example 1: Basic Reshaping
Let's say you have a 1D array and you want to reshape it into a 2D array.

In [56]:
import numpy as np

# Create a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape it into a 2D array with 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array (2x3):")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6]

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]


### Example 2: Using -1 to Automatically Calculate One Dimension
If you're unsure about one dimension of the new shape, you can use -1, and NumPy will automatically calculate it for you based on the total number of elements.

In [58]:
import numpy as np

# Create a 1D array with 9 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

reshaped_arr = arr.reshape(3, -1)

print("Original Array:")
print(arr)

print("\nReshaped Array (3x3):")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6 7 8 9]

Reshaped Array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Example 3: Reshaping with Column-Major Order
You can also reshape the array using a different reading and writing order (column-major order). This is less common but may be useful in some cases.

In [59]:
import numpy as np

# Create a 2x3 array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape it to 3x2 using 'F' for column-major order
reshaped_arr = np.reshape(arr, (3, 2), order='F')

print("Original Array:")
print(arr)

print("\nReshaped Array (3x2) in Column-Major Order:")
print(reshaped_arr)

Original Array:
[[1 2 3]
 [4 5 6]]

Reshaped Array (3x2) in Column-Major Order:
[[1 5]
 [4 3]
 [2 6]]


### 2. Numpy `flatten()` in NumPy

The 'flatten()' method in NumPy is a useful function when you want to convert a multi-dimensional array (like a 2D, 3D array, etc.) into a **1D array**.

### What Does flatten() Do?

- Creates a new 1D array: The method takes all elements from the multi-dimensional array and arranges them into a single, 1D array.

- Order of elements: The elements are placed into the 1D array in a specific order, which can be controlled. By default, it follows row-major order (similar to how a C programming language would store data), but you can change it based on your requirements.

#### Syntax
```python
ndarray.flatten(order='C')
